package fr.formation.students.string;

public class StringApplication {
    public static void main(String[] args) {
        String[] words = LOREM.split(" ");
        String a = "a";
        String b = "b";
        String c = "c";
        String d = a + b + c;
        concat(words);
        stringBuilder(words);

    }
    // use == only for primitive type

    private static void stringBuilder(String[] words) {
        long start = System.currentTimeMillis();
        StringBuilder result = new StringBuilder();
        for (String word : words) {
            result.append(word);
            result.append(" ");
        }
        long end = System.currentTimeMillis();
        System.out.println("StringBuiler " + (end - start) + " ms");
    }

    private static void concat(String[] words) {
        long start = System.currentTimeMillis();
        String result = null;
        for (String word : words) {
            result += word + " ";
        }
        long end = System.currentTimeMillis();

        System.out.println("concat took " + (end - start) + " ms");
    }

    private final static String LOREM = "Lorem Ipsum\n" +
            "\"Neque porro quisquam est qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit...\"\n" +
            "\"There is no one who loves pain itself, who seeks after it and wants to have it, simply because it is pain...\"\n" +
            "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin a vestibulum nisl. Vestibulum ligula metus, vulputate vitae lectus non, commodo interdum urna. Sed id nulla a diam rutrum gravida. Praesent a tristique neque. Mauris at neque nulla. Proin non convallis enim. Cras eu imperdiet purus, eu lacinia mauris. Duis tempus erat tortor, nec finibus est sagittis vitae. Nullam tellus magna, condimentum vitae rutrum eu, eleifend vitae justo. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Phasellus eget laoreet arcu. Nam eu arcu quis leo vehicula malesuada.\n" +
            "\n" +
            "Fusce id nunc laoreet, lobortis sapien a, malesuada mauris. Etiam fringilla lectus non nunc imperdiet sagittis. Nunc finibus sed libero vel aliquam. Proin non rutrum tellus. Cras laoreet magna ligula, at tempus tellus pharetra eget. Phasellus eleifend ut elit in tincidunt. Morbi molestie elit a dolor ultricies, ac eleifend lacus pretium. Curabitur eu neque fermentum, interdum metus eget, condimentum nibh. Sed et lectus posuere, congue velit eu, egestas justo. Sed dignissim, eros et pulvinar feugiat, arcu nunc euismod turpis, elementum molestie tortor arcu at dolor.\n" +
            "\n" +
            "Mauris sed ex nec justo imperdiet aliquet vitae at arcu. Donec aliquet aliquam venenatis. Pellentesque lobortis lacinia orci, a bibendum enim. Cras id urna vehicula, ornare enim non, feugiat dui. Suspendisse porta cursus lorem non accumsan. Suspendisse quis malesuada dui. Sed vulputate ante nec varius volutpat.\n" +
            "\n" +
            "Nam ut eros ornare, egestas quam ut, gravida mauris. Quisque vel interdum arcu. Vestibulum ac est dapibus, iaculis dolor non, ornare justo. Nam volutpat tristique dui ut laoreet. Nulla facilisi. Aliquam erat volutpat. Integer nec ex eros. Sed elementum nibh turpis, sed vulputate arcu efficitur quis. Morbi sollicitudin tortor nibh, ac auctor velit interdum ut. Aenean tempor orci urna, vitae finibus magna sagittis ac. Morbi vestibulum diam non est efficitur congue. Donec a tempor leo, ut facilisis metus. Donec ut viverra ex. Nulla vitae elit sagittis, euismod risus sed, auctor orci.\n" +
            "\n" +
            "Vestibulum sit amet tortor sed ante volutpat egestas. Duis feugiat, turpis nec cursus hendrerit, elit tortor consequat libero, eu vehicula ex dui gravida leo. Fusce in placerat nulla. Nullam vitae lorem ligula. Nam et vehicula quam. Sed tincidunt, mauris vitae finibus finibus, tellus massa laoreet nisl, at tempor eros felis at augue. Integer varius malesuada mauris. Vestibulum a massa urna. Donec risus orci, ullamcorper vel magna non, mattis tempus enim. Quisque ultrices magna quis odio tincidunt, in lacinia tellus ultricies. Donec ac laoreet orci. Nam tristique viverra tincidunt.\n" +
            "\n" +
            "Aenean volutpat mauris vel sagittis tincidunt. Cras libero orci, finibus a sem et, tempus auctor nisi. Sed ac ipsum efficitur, porttitor massa eget, faucibus ex. Aliquam lacinia euismod bibendum. Sed vitae viverra erat. Nullam venenatis scelerisque lacus eu tempus. Ut nec malesuada leo, eu ornare metus. Sed eleifend magna aliquet eros iaculis ultricies.\n" +
            "\n" +
            "Suspendisse elementum vestibulum nisl, ac pharetra nulla eleifend a. Maecenas semper molestie auctor. Nullam posuere sit amet nunc ac rhoncus. Pellentesque lobortis mollis mi, eget sagittis massa venenatis sed. Pellentesque dignissim lacus magna, mattis viverra mi porttitor finibus. Nulla odio augue, elementum non varius vitae, condimentum vitae enim. Nunc sagittis dui eget turpis aliquet laoreet. Etiam sed odio a enim sollicitudin ultricies. Nullam rutrum neque quis mauris interdum finibus. Pellentesque ac magna ut ex gravida elementum. Quisque ac mauris nec mauris molestie lobortis nec ac ante. Sed commodo hendrerit molestie. Sed nec rutrum dolor.\n" +
            "\n" +
            "Pellentesque ex nisl, tincidunt vitae lorem ut, consequat ullamcorper massa. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin non mattis orci. Maecenas mi eros, porttitor eget consequat et, blandit vel nisl. Aliquam fermentum dui dui. Pellentesque hendrerit enim dignissim, ultricies neque rhoncus, pretium arcu. Vestibulum pulvinar volutpat diam. Fusce tortor neque, porta eu auctor quis, tristique vitae lacus. Vivamus quis pulvinar dui. Nulla blandit augue nec orci ultricies porta. Maecenas nibh nisi, dictum et elit at, efficitur feugiat quam.\n" +
            "\n" +
            "Aliquam rhoncus urna at ligula dictum dignissim. Sed pulvinar placerat elit, id maximus orci hendrerit ac. Proin pulvinar ipsum nec est malesuada placerat. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. In hac habitasse platea dictumst. Proin venenatis dignissim nisl, ut sagittis tellus lacinia a. Ut facilisis facilisis aliquet. Sed maximus elementum arcu.\n" +
            "\n" +
            "Integer elementum tempus nisi ut sagittis. Nam efficitur enim a purus pharetra aliquet. Quisque nisl odio, scelerisque vel rutrum sit amet, aliquam et neque. Pellentesque et dolor mollis, tempor tellus tempor, tempor est. Quisque vel ex in eros malesuada faucibus nec sit amet diam. Quisque ligula risus, varius nec iaculis nec, accumsan sit amet sem. Proin id molestie neque. Ut eget diam dui.\n" +
            "\n" +
            "Suspendisse sapien purus, fermentum a tincidunt vitae, molestie at tellus. Suspendisse lectus leo, cursus nec urna sed, vestibulum rhoncus nisi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc sed justo volutpat, feugiat dolor at, dignissim sem. Praesent ullamcorper pellentesque diam. Mauris efficitur laoreet nunc, vitae pharetra metus tempus nec. Integer mauris eros, vulputate ut egestas vel, bibendum vitae mi.\n" +
            "\n" +
            "Nulla a vehicula urna. Pellentesque sed nibh malesuada, tristique metus nec, scelerisque tortor. Donec molestie varius sapien, eu convallis erat fermentum vitae. Curabitur maximus, est eu rhoncus sollicitudin, est metus egestas ante, ut placerat tellus ipsum nec nisl. Vivamus eget lacinia mi. Proin luctus imperdiet mattis. Maecenas sit amet fermentum urna.\n" +
            "\n" +
            "Proin a congue libero. Donec mi velit, aliquet a purus in, scelerisque malesuada risus. Sed lobortis, quam a ullamcorper elementum, nisl justo varius odio, non ornare purus diam eget urna. Sed quis mollis diam. Fusce euismod dui mi. Phasellus sed vestibulum urna, eget faucibus nisl. Curabitur eu felis imperdiet, porta orci quis, ultricies est. Nulla faucibus eros et leo feugiat fermentum. Aenean interdum molestie enim, ut tempor lorem suscipit in. Vestibulum volutpat, lorem eget consectetur tristique, risus ligula facilisis ligula, non imperdiet ipsum massa ac risus.\n" +
            "\n" +
            "Aenean interdum imperdiet pellentesque. Etiam sollicitudin consequat urna, eget hendrerit arcu cursus ultrices. Aenean magna libero, dictum quis malesuada nec, commodo in orci. Morbi auctor nisi ipsum, quis dictum metus malesuada a. Nullam ultricies eros sed est auctor, quis placerat felis lacinia. Curabitur at ornare erat, in finibus diam. Fusce bibendum, lacus quis commodo congue, dolor est venenatis lacus, quis euismod mauris massa et mauris. In efficitur, lorem sit amet suscipit varius, dolor lorem varius nulla, vel mattis arcu erat eu purus. Pellentesque a ornare ante. Ut eu lobortis mauris, non auctor nisi. Aliquam sem lorem, fermentum sed nulla nec, mollis convallis orci. Maecenas vehicula sollicitudin hendrerit.\n" +
            "\n" +
            "Proin ut rutrum felis. Morbi suscipit diam ut sodales gravida. Nam rhoncus sed diam sit amet ultricies. Maecenas pharetra lacinia lacus non tincidunt. Donec vel mauris et lorem vehicula varius ut in libero. Vestibulum condimentum, leo quis tempus blandit, magna purus egestas orci, sit amet posuere ipsum augue quis nunc. Nunc cursus, dui sit amet auctor interdum, sapien est pulvinar leo, vitae tempus ipsum massa ut dolor. Donec pretium enim pharetra massa rhoncus, ac venenatis metus interdum.\n" +
            "\n" +
            "Etiam ac odio et erat placerat convallis. Vestibulum eu rutrum orci, a suscipit justo. Praesent varius justo odio, laoreet tristique massa porttitor eget. In hendrerit volutpat enim eget blandit. Vestibulum id ante eu felis finibus dictum. Maecenas pharetra lacus non blandit auctor. Sed posuere metus non tempor fermentum. Donec ultricies, nisl et congue commodo, risus velit gravida nisi, at dictum nunc est a nunc. Pellentesque tincidunt justo eu odio consectetur, vitae luctus mi sodales. Sed eu velit sapien. Aenean non quam a mi faucibus iaculis at eu ipsum. Morbi ac neque ac elit commodo pellentesque. Mauris facilisis orci nec nulla pharetra pulvinar. Mauris eu magna vulputate, hendrerit turpis id, sodales turpis. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis facilisis gravida sapien ut suscipit.\n" +
            "\n" +
            "Vestibulum eget sodales diam. Cras eget mauris tincidunt, pretium lectus lobortis, maximus sem. Pellentesque dui libero, placerat ut gravida id, egestas eu leo. Sed tincidunt sem ac felis condimentum, id venenatis lorem venenatis. Mauris volutpat diam eros, nec ultrices magna facilisis ac. Nullam finibus, ligula non imperdiet semper, elit justo facilisis elit, vel ultrices ipsum tellus eget enim. Pellentesque dapibus, leo quis commodo fringilla, orci lectus convallis nisi, et iaculis nibh leo ut magna. Duis ipsum libero, eleifend finibus felis sollicitudin, placerat pellentesque nunc. Vivamus pellentesque dolor mi, nec accumsan tellus fermentum et. Phasellus sed hendrerit elit. Nam aliquam odio sit amet arcu mollis suscipit. Fusce aliquet aliquam ex eu dictum. Donec lacinia egestas velit, nec efficitur tellus ultricies laoreet.\n" +
            "\n" +
            "Sed tristique ipsum in dolor mattis lobortis. Morbi mollis dui sed ultricies sollicitudin. Integer quis gravida urna. Suspendisse faucibus auctor nunc non congue. Nunc vel est augue. Integer justo mauris, consequat a nibh sit amet, mattis pharetra neque. Nam fringilla finibus leo. Ut a mi in velit facilisis elementum.\n" +
            "\n" +
            "Maecenas nec diam ex. Phasellus faucibus malesuada metus, quis scelerisque nibh viverra nec. Aenean commodo sed dui ac dignissim. Sed justo turpis, egestas id tincidunt vel, consequat quis ligula. Quisque condimentum iaculis tristique. Integer dui dui, hendrerit id lorem quis, pretium cursus tellus. Praesent molestie felis sit amet sem convallis, in faucibus justo porttitor. Nullam tempus vel mi ac porttitor. Quisque ac enim dapibus, ornare diam quis, interdum eros.\n" +
            "\n" +
            "Praesent ullamcorper ligula quam, ac blandit lacus posuere id. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nam eleifend nisl non ex sollicitudin, vitae hendrerit erat tristique. Sed et magna et dolor ultrices eleifend nec eget dolor. Ut imperdiet feugiat rhoncus. Proin vel libero nec lacus ultrices vehicula. Pellentesque quis lorem ullamcorper, convallis urna ac, posuere ligula. Cras non enim ullamcorper, venenatis risus quis, molestie magna. Proin congue metus vel lacinia pellentesque. Quisque scelerisque nulla augue, sit amet mollis mi pharetra eget. In tristique purus id sem tempus, ac vehicula mi dignissim. Suspendisse condimentum iaculis mi, a maximus turpis pulvinar in.\n" +
            "\n" +
            "Aliquam erat volutpat. Suspendisse at dictum nunc. Donec volutpat non dolor nec maximus. Praesent ac tristique est. Integer aliquet libero in tincidunt pulvinar. Curabitur at ligula neque. Phasellus vel ligula nisl. Nullam nec lectus sit amet metus ultrices ultrices in id nunc. Aenean non lacus a massa fermentum maximus a eleifend quam. In congue vel lacus et tincidunt. Integer at interdum nunc, et ullamcorper ante.\n" +
            "\n" +
            "Suspendisse eget mi vel odio efficitur sagittis quis vel ante. Nunc sit amet lectus scelerisque, faucibus quam eu, placerat urna. Pellentesque a eros nec justo fringilla condimentum. Donec suscipit ligula in efficitur tincidunt. Fusce sagittis ipsum at condimentum consectetur. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas efficitur tincidunt varius.\n" +
            "\n" +
            "Phasellus sed turpis tortor. Curabitur in imperdiet libero. Duis leo eros, congue sit amet pulvinar at, faucibus ac sem. Etiam vehicula pretium velit, maximus blandit dui pretium id. Fusce congue eget dolor a molestie. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\n" +
            "\n" +
            "Etiam ligula ligula, laoreet quis blandit condimentum, feugiat eu orci. Duis malesuada ante sapien, ac blandit risus varius vel. Nullam at gravida ipsum. Suspendisse eget egestas eros, non lacinia mauris. Sed sit amet dolor a velit laoreet cursus. Praesent suscipit, sem ac vulputate placerat, urna mi dignissim orci, non fermentum dolor leo non odio. Sed efficitur, neque eu tempor lacinia, nisi justo finibus neque, sed consequat felis erat at arcu. Donec a magna a ex dictum cursus nec et tellus. Donec cursus, ligula eu rhoncus porttitor, dolor dolor efficitur odio, commodo facilisis justo lorem quis ante. Donec aliquet vitae libero et molestie. Quisque libero nisi, porttitor vitae lectus nec, tincidunt varius massa. Aenean iaculis, ante eget varius maximus, risus orci tincidunt justo, ornare faucibus dui massa non massa. Sed feugiat arcu vitae interdum consectetur. Phasellus ex felis, sagittis tincidunt neque sed, scelerisque mattis mauris.\n" +
            "\n" +
            "Aenean dapibus massa id nisl viverra, ac semper sem malesuada. Praesent vestibulum tellus sed metus ornare, id posuere felis finibus. Nullam in velit at neque aliquam aliquet. Suspendisse mi ex, maximus vel fermentum vel, varius at tortor. Etiam quis faucibus enim. Fusce porttitor enim at consectetur finibus. Nulla eget turpis sit amet felis varius viverra. Mauris varius nibh et dui dictum fringilla. Aliquam urna ligula, pellentesque at ornare quis, ornare ac orci. Donec dapibus faucibus cursus. Pellentesque sodales sollicitudin sapien, non aliquet dolor.\n" +
            "\n" +
            "Pellentesque varius commodo blandit. Nulla diam ligula, condimentum quis urna et, suscipit tincidunt ante. Aliquam hendrerit ornare lorem. Cras convallis eget lectus eu dignissim. Aenean nec lacus a justo posuere venenatis a nec dolor. Suspendisse potenti. Etiam eu nisl eget velit rutrum feugiat vel eget turpis. Sed at nulla tortor. Vestibulum et ligula ac velit fringilla suscipit at quis nibh.\n" +
            "\n" +
            "Aliquam a faucibus metus. Curabitur ornare elit nec ipsum tempus, in blandit nisl hendrerit. Nam molestie et mauris a dapibus. Donec lobortis volutpat est nec ornare. Aenean nec molestie libero, vel ornare lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Etiam vitae mattis diam, sit amet sollicitudin leo.\n" +
            "\n" +
            "Sed metus neque, vestibulum sed imperdiet eu, consectetur sodales ligula. Pellentesque bibendum turpis id dui tristique, sit amet blandit lorem iaculis. Phasellus efficitur eget diam non blandit. Aliquam erat volutpat. Curabitur non pulvinar est. Phasellus ut dolor mauris. Praesent sed elit ac urna faucibus ultricies laoreet eget elit. Phasellus ullamcorper id eros a facilisis. Sed ipsum nisl, sagittis sit amet luctus ac, scelerisque vel quam. Praesent a diam a odio bibendum aliquam. Donec tempor libero dignissim massa ultrices volutpat. Maecenas commodo lectus vel ornare aliquam. Mauris porttitor viverra turpis a malesuada. Vestibulum et est egestas, pellentesque sapien eget, tristique massa. Nam et tincidunt mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.\n" +
            "\n" +
            "Sed efficitur ac felis ut vehicula. Duis nunc mauris, placerat eget dapibus vitae, efficitur vitae sem. Aliquam quis ex tristique, condimentum magna at, facilisis est. Phasellus sit amet bibendum massa. Mauris lacinia neque neque, nec varius metus placerat nec. Sed aliquet vulputate vestibulum. Sed non nibh scelerisque, scelerisque lectus quis, efficitur augue. Nam tincidunt vitae dolor eu posuere. Ut auctor iaculis hendrerit. Aenean sed rutrum tellus. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Integer rutrum tincidunt libero in auctor. Etiam imperdiet sed nisl imperdiet rutrum. Curabitur interdum dictum consectetur. Suspendisse potenti. Aenean odio lacus, eleifend ac blandit sit amet, tempor vitae mi.\n" +
            "\n" +
            "Sed commodo non eros sed interdum. Curabitur ac consequat neque. Morbi in nunc id dolor lobortis convallis in in lacus. Integer imperdiet eleifend magna id accumsan. Phasellus congue mattis mauris, sed rutrum sem varius sit amet. Aliquam et sagittis nunc, sed aliquet libero. Ut rutrum consectetur ex eget varius. Morbi a sagittis lacus.\n" +
            "\n" +
            "Sed elit metus, tincidunt volutpat aliquet quis, rutrum non lorem. Quisque quis metus rhoncus, auctor enim in, maximus ligula. Nullam mattis congue nisl, condimentum semper risus venenatis vitae. Sed leo felis, blandit non varius sit amet, vestibulum in mauris. Nunc convallis, diam non aliquet dapibus, metus leo sollicitudin quam, ac facilisis purus purus eu ex. Vestibulum pulvinar nisi ut neque imperdiet tristique vel a sapien. Suspendisse pulvinar orci et sollicitudin venenatis. Proin sit amet ligula ut diam finibus maximus. Fusce tincidunt, neque quis elementum ultrices, metus dui tincidunt dolor, sit amet dignissim elit mauris a magna. Nulla accumsan libero vel orci auctor, at egestas dui aliquet. Morbi ut bibendum nunc.\n" +
            "\n" +
            "Vivamus vel elit eget sem faucibus vestibulum. Integer sit amet tortor in nisi ultrices dignissim sed vitae libero. Ut luctus fermentum ligula, sit amet suscipit tellus aliquam a. Nulla vitae volutpat metus. Integer magna ipsum, lacinia quis volutpat ut, fringilla vel est. Donec id dapibus metus. Nam eget mauris vitae velit convallis placerat eu vel arcu. Etiam eu fringilla risus. Nunc urna dui, suscipit in metus at, porttitor tristique lectus. Vivamus tellus justo, ultrices a vulputate nec, pretium sed ipsum.\n" +
            "\n" +
            "Morbi ullamcorper in mi vitae aliquam. Sed in molestie odio. Quisque rhoncus sapien in lectus vestibulum, consectetur sollicitudin mauris aliquet. Morbi orci elit, malesuada sed fringilla a, laoreet id enim. Aenean iaculis finibus malesuada. Quisque pulvinar, lorem sed volutpat euismod, eros turpis laoreet nisi, sit amet auctor augue felis consectetur purus. Fusce vel est quis mi cursus ultricies vitae at metus. Aliquam erat volutpat. Pellentesque maximus gravida tincidunt. Ut sed condimentum purus. Pellentesque sit amet libero tempus, consequat leo sit amet, facilisis mauris. Proin eu sapien a nisl suscipit tristique non ac sem. Pellentesque erat tellus, gravida vitae condimentum at, volutpat ac mauris. Nulla imperdiet metus in lacus sollicitudin dictum.\n" +
            "\n" +
            "Maecenas posuere lorem eget diam suscipit, eu tristique dolor porttitor. Ut et sem ut magna ultrices lobortis. Praesent semper erat vel quam pellentesque facilisis. Proin nec diam vestibulum, lacinia ipsum non, laoreet augue. Duis aliquam nulla non purus lacinia, ac luctus arcu sagittis. In pharetra non neque sed semper. Suspendisse tincidunt pulvinar tincidunt. Suspendisse cursus laoreet pellentesque. Pellentesque accumsan turpis ut neque vulputate, nec maximus eros venenatis. Aliquam a velit libero. Sed id libero tempor velit euismod sollicitudin eu id ante. Donec in enim luctus, congue magna vel, accumsan nulla. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.\n" +
            "\n" +
            "Nunc ligula tortor, imperdiet quis luctus non, laoreet in quam. Fusce neque risus, accumsan in sem eu, sodales facilisis justo. Vestibulum enim diam, congue eu lorem eget, auctor pharetra lacus. Phasellus porttitor neque a mi luctus facilisis. Nulla dui nisi, hendrerit bibendum maximus sit amet, eleifend quis ipsum. Etiam elementum sem ac turpis cursus, et dapibus diam sodales. Sed aliquet iaculis enim, non eleifend velit mollis vel. Nullam ut dapibus diam, quis venenatis ante. Aliquam eu commodo augue, at vestibulum magna. Praesent egestas, leo vel efficitur fermentum, risus mi mollis sapien, a elementum dolor diam pulvinar erat. Nulla in aliquam lectus. Duis tincidunt porttitor ipsum sed fringilla.\n" +
            "\n" +
            "Duis cursus, orci ac posuere semper, quam neque bibendum nunc, eu iaculis nibh odio eget mi. Sed rutrum iaculis ipsum. Proin porta nisl a turpis iaculis, nec condimentum quam consequat. Phasellus tristique vulputate vulputate. Morbi non diam quis nunc fringilla dapibus. Praesent ut cursus eros. Sed in magna orci. Nulla vehicula, est ac elementum euismod, diam erat varius odio, quis fermentum felis urna at urna. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Nunc vitae varius urna. Sed lacinia, lorem vel volutpat fringilla, eros urna finibus mauris, ut consectetur leo metus non ante. Curabitur feugiat consequat rutrum. Suspendisse potenti. Donec quis ex nec arcu interdum gravida. Fusce quis elit et quam sodales sodales ut id odio. Interdum et malesuada fames ac ante ipsum primis in faucibus.\n" +
            "\n" +
            "Morbi vehicula viverra orci vitae cursus. Duis placerat ornare malesuada. Pellentesque vulputate id elit in suscipit. Nam nec nisl vel nisl consequat egestas a vel magna. Nulla a dui nec massa tincidunt gravida. Sed sit amet sagittis lacus, eget facilisis augue. Phasellus eleifend diam quis ornare commodo.\n" +
            "\n" +
            "Donec et interdum elit. In hac habitasse platea dictumst. Donec consectetur nibh augue, in ornare diam blandit at. Nunc sed mauris quis turpis volutpat imperdiet. Sed tempus mauris non dui egestas, quis cursus diam commodo. Phasellus laoreet massa et congue pretium. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Mauris et diam urna. Vestibulum non lacus vel risus iaculis sodales.\n" +
            "\n" +
            "Duis mattis leo et orci semper malesuada. Etiam eleifend tortor vitae purus finibus, eu pulvinar eros ullamcorper. Praesent in blandit augue. Aliquam erat volutpat. Etiam eleifend eros id orci luctus porttitor. Aenean ultricies sodales lacus, vel dignissim est lacinia vitae. Maecenas suscipit lobortis ex cursus tristique. Ut viverra venenatis justo nec pulvinar. Ut tempor sapien luctus commodo blandit. Mauris mollis sapien arcu, quis gravida arcu accumsan ac. Cras sit amet porttitor quam. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Cras lacus libero, efficitur vel fermentum dictum, feugiat vitae nunc.\n" +
            "\n" +
            "Sed dignissim lacinia tellus, pretium interdum dui tristique id. Duis fermentum, ligula vitae mattis vulputate, quam purus mollis massa, nec faucibus est diam et felis. Nunc porttitor orci at imperdiet semper. Suspendisse potenti. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Ut cursus nisl ac gravida posuere. Nulla sed felis accumsan, laoreet tortor eu, placerat lorem. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Suspendisse convallis leo eget urna viverra maximus. In ullamcorper nisl elementum quam mollis, nec sagittis magna congue. Lorem ipsum dolor sit amet, consectetur adipiscing elit.\n" +
            "\n" +
            "Nulla eu facilisis ante, eu pulvinar sem. Quisque dapibus libero at tempus fermentum. Integer pulvinar dui id erat ullamcorper, vitae pharetra dolor laoreet. Fusce id dapibus nibh. Sed a ante et odio tristique vehicula in sed lacus. Ut consectetur consectetur sem. Nam mi nunc, pellentesque sit amet lacinia sit amet, vestibulum at nunc. Aliquam cursus congue eros ac aliquam. Ut commodo eget lorem ac pharetra. Aliquam ut rhoncus nibh. Praesent eleifend tincidunt orci eu porta. Phasellus eget nisl magna. Nam aliquet placerat dictum. Aenean nec nulla sapien. Etiam viverra nec ipsum a luctus. Aenean aliquet convallis felis ac vestibulum.\n" +
            "\n" +
            "Ut nec auctor eros. Sed neque lacus, laoreet ut laoreet non, elementum ut nulla. Curabitur rutrum ex ut dolor lobortis, in pretium orci mattis. Nullam volutpat a lectus a ultrices. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. In gravida malesuada mauris, ut efficitur odio tincidunt ac. Mauris mollis ultrices enim vitae pharetra.\n" +
            "\n" +
            "Maecenas eu convallis libero. Integer sed purus vitae purus sagittis tristique. Mauris sed mi ante. Proin vulputate scelerisque dictum. Vestibulum elementum, orci in tempus placerat, sapien felis consectetur urna, in ornare leo nisl eget tortor. Vestibulum scelerisque, enim volutpat accumsan finibus, mi justo auctor neque, eget porttitor dui mauris nec risus. Aliquam sodales arcu fermentum, ultrices massa et, dictum nulla. Pellentesque eleifend mi sed turpis euismod, semper vehicula libero porta. Donec vitae odio blandit felis pretium ultricies.\n" +
            "\n" +
            "Morbi eu nunc sed purus lacinia fermentum. Donec euismod sapien enim, a convallis ipsum posuere vel. Sed cursus, massa ut posuere venenatis, nulla justo ultrices nunc, sed tincidunt dui justo et lectus. Cras hendrerit diam id elit finibus, nec convallis mauris sodales. Curabitur ornare condimentum arcu, vitae finibus ligula viverra ut. Vestibulum elit eros, interdum quis tellus ut, tincidunt mollis eros. Donec sed tincidunt quam. Nullam augue augue, suscipit quis dolor eget, sagittis egestas eros. Curabitur ex arcu, mattis in rhoncus id, finibus ut arcu. Proin eget neque ultricies, egestas leo pellentesque, fermentum dui. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.\n" +
            "\n" +
            "Cras augue ligula, fringilla nec lectus non, feugiat pharetra ipsum. Integer orci mi, tincidunt a felis ac, feugiat eleifend tellus. Proin vulputate ipsum ultricies dictum accumsan. Aenean commodo aliquet augue. Aenean ullamcorper tempus nunc, sit amet dictum dolor euismod nec. Maecenas in ex magna. Phasellus diam ligula, volutpat eget laoreet at, rhoncus eu risus. Nullam a purus tellus. Maecenas nisi ex, tristique quis tellus eget, accumsan vehicula libero. Morbi dapibus semper sapien id porttitor. Ut tempus mauris in libero condimentum iaculis.\n" +
            "\n" +
            "Donec volutpat rhoncus vulputate. Nulla sit amet leo tempus, vehicula nibh in, suscipit tortor. Nunc pretium, arcu et mollis euismod, velit quam rutrum arcu, nec posuere quam leo ac enim. Duis semper, lectus et maximus laoreet, tellus nibh mattis augue, ac malesuada augue ante id est. Aliquam sed urna eu lectus pretium fringilla. Aliquam et aliquet mi. Proin non velit non neque fermentum finibus ac dapibus tellus. Etiam eu magna tellus.\n" +
            "\n" +
            "In nec tempus est, in vulputate est. Nunc pretium lectus a sapien sollicitudin fringilla id id dui. Vestibulum nisi libero, tempor consectetur mauris eget, sodales condimentum urna. Maecenas non gravida odio. Praesent in nulla lorem. Morbi et blandit est. Duis venenatis nisl et dui fermentum iaculis. Etiam sed elit turpis.\n" +
            "\n" +
            "Nunc dapibus, tortor eget lobortis malesuada, arcu velit iaculis nunc, at porttitor mi lorem in mauris. Phasellus at enim vel metus bibendum interdum consequat vel augue. Etiam sit amet dignissim velit. Duis malesuada a mauris vitae fermentum. Praesent nec risus libero. Proin in lectus varius, bibendum dolor at, pellentesque mi. Donec tincidunt consequat lectus, eu ultricies mi posuere eu.\n" +
            "\n" +
            "In in ante semper, auctor lacus a, gravida erat. Ut vel hendrerit nisi, et fermentum felis. Fusce luctus augue eu ex luctus rutrum. Donec viverra tortor vitae magna viverra laoreet. Etiam eu rutrum dolor, et facilisis sapien. Fusce et augue pulvinar, porta arcu vel, convallis dolor. Nullam vel turpis sagittis sem mattis placerat. Maecenas luctus odio a ex vestibulum semper. Phasellus in nisl tortor. Pellentesque ultrices erat porta commodo placerat. Etiam viverra lobortis mi, ut dapibus purus.\n" +
            "\n" +
            "Curabitur sit amet dolor odio. Donec nec pretium dui. Nam condimentum ante dolor, ac aliquam nisl dapibus quis. Aliquam erat volutpat. Etiam consectetur ornare sollicitudin. Aliquam non massa posuere, laoreet dui ac, tristique nulla. Vestibulum sodales eget velit ut pulvinar. Nunc sodales nunc enim, id rutrum justo bibendum sit amet. Aenean a eleifend ex. Nunc eleifend a nulla eget rutrum. Sed non cursus turpis, eget auctor risus.";
}
